### PR TITLE
Sv/sorted dict 2

### PR DESCRIPTION
**Pull request by kmsquire**
This is an implementation of a SortedDict type, by @StephenVavasis.  This was previously submitted as  #70, and is only presented here in a form slightly more suitable for review/merging.  All commits belong to Stephen, with very minor modifications.

#### Features

* based on 2-3 trees
* 1.5-2x the speed of equivalent C++ code (as tested by Stephen--see the README for details)
* a token interface for keeping reference to previously located items in the dictionary

The code includes a large amount functionality (and code), as well as substantial documentation and a good set of tests.  

#### History

Stephen originally submitted this back in August (see #52 and #53).  I've been the main reviewer so far, and believe it is in good enough shape to merge.  It could use another set of eyes, though, if someone is up to the task.  

At a minimum, it would be great if someone could read through the documentation.  (Cc: @ViralBShah, @StefanKarpinski, @dpsanders, @aviks)

#### For Consideration

1. Stephen wasn't happy with markdown formatting for the documentation, and rewrote the README as restructuredText.
2. The implementation stores uses the first inserted item in sentinel values marking the beginning and end of the list.  References to this item will be maintained (and finalizers will not be run) even if the item is removed from the tree.
3. Equality testing is slightly non-standard.

@StephenVavasis, please add any additional information you feel is needed, and correct any misinformation above.

### CODE REVIEW

**Comment by garborg** [comment]
Awesome to see this coming together. Hoping this leads to a token interface in Base :candy:

**Comment by StephenVavasis** [comment]
One note to add: I had originally planned to create three sorted 
containers, namely SortedDict, SortedMultiDict, and SortedSet.  After 
discussions with Kevin Squire, I decided to create only SortedDict in this 
pull request and leave SortedMultiDict and SortedSet for a future PR. 
However, the documentation has been organized in a way that foreshadows 
the other two containers.

And a small point to add: when I rewrote the documentation in RST, I left 
the coveralls invocation unchanged at the beginning of the file.  In MD, 
the coveralls invocation did not display because it was interpreted as a 
comment.  However, it is not interpreted as a comment by RST and so it is 
inappropriately displayed.  I don't know how coveralls works, so I don't 
know how to fix this.  I would appreciate it if someone else could fix it 
or tell me how.

-- Steve

**Comment by kmsquire** [comment]
Thanks for bringing that up, Stephen.

Fixing the badges at the top of the README was one of the small changes I
actually did make. The other was that the README was encoded as UTF32,
which made it appear as a binary file in the original PR. I changed it to
UTF8.

**Comment by kmsquire** [comment]
Bump.  I'm going to merge this later today or tomorrow unless there are any objections.

**Comment by garborg** [comment]
Bump. I'd like to clear out all the deprecation warnings in the package, but I don't want to get in the way of this PR.

**Comment by kmsquire** [comment]
Thanks for the bump, Sean.

**Pull request merged**
