### PR TITLE
WIP: Added functionality to sort (some) dictionaries.

### PR DESCRIPTION
**Pull request by kmsquire**
This needs some more testing and a little cleaning up, but it should be in pretty good shape.

Ref: https://groups.google.com/d/topic/julia-users/e1Pk6rjh6Ao/discussion (although it's not entirely relevant)

### CODE REVIEW

**Comment by femtotrader** [comment]
Is there any chance to have this PR merged?

**Comment by kmsquire** [comment]
It's funny, I just remembered this PR yesterday. Thanks for the ping. 

The `OrderedDict` type has been redone since this was submitted, but reworking it for the new version should be pretty straightforward. I'll try to take a look today.

**Comment by kmsquire** [comment]
Superseded by @225

**Comment by femtotrader** [comment]
#225

**Pull request closed without merging**
