### PR TITLE
Sorted dict 2

### PR DESCRIPTION
**Pull request by StephenVavasis**
This pull request contains the latest version of the SortedDict code and documentation, and additionally includes the recent suggestions from Kevin Squire for usage of the 'compat' package in testing (so that the tests run in both Julia 0.3 and 0.4) and the use of the @test macro in the test file instead of the @assert macro.

### CODE REVIEW

**Comment by aviks** [comment]
This build failed since `REQUIRE` does not include the `Compat` package

**Comment by StephenVavasis** [comment]
I fixed the REQUIRE file, and I also fixed a typo in the documentation.

**Comment by StephenVavasis** [comment]
I added Compat to the REQUIRE file, pushed the new commit to the server, 
and added a comment to #70.  Is my pull request still active, or do I need 
to somehow reactivate it?

(Kevin: I have cc'd your gmail account on this message because I can't 
tell if you will get this message through another channel.)

-- Steve

**Comment by kmsquire** [comment]
Hi Stephen, thanks for the email. I've been swamped, but hope to get to
this tomorrow.  I'm hoping we can just merge.  Thanks for your patience.

Avik,  thanks for taking a quick look.

Cheers, Kevin

**Comment by kmsquire** [comment]
Merged in #71

**Pull request closed without merging**
