### PR TITLE
tree.jl

### PR DESCRIPTION
**Pull request by mtabor150**
Both tree.jl and balancedTree.jl have TreeNode types, so I renamed the version in tree.jl to avoid a type redeclaration conflict.

### CODE REVIEW

**Comment by hayd** [comment]
cc @StephenVavasis, @kmsquire and #71

**Comment by matthieugomez** [comment]
Can someone merge this? Tree.jl is not included in the package for now.

**Comment by hayd** [comment]
I wonder if TreeNode should be abstract, and balancedTree's types should subtype TreeNode and Tree.

**Comment by kmsquire** [comment]
Working my way through old issues, slowly.  Thanks to @hayd for bumping this one.

The current version of `tree.jl` really was implemented as an example.  It wasn't implemented with efficiency in mind, and lacks almost any useful functionality.  The current implementation of `SortedDict`s should suffice for now.

I'm going to close this for now, and submit a PR which removes `tree.jl` from the repo.

**Pull request closed without merging**
