### PR TITLE
replace README docs with link to readthedocs

### PR DESCRIPTION
**Pull request by rawls238**
@kmsquire @DanielArndt 

Let me know if you guys think any changes should be made to the docs before merging this in: 

http://datastructuresjl.readthedocs.org/en/latest

@kmsquire I'm not sure if the `readthedocs` github webhooks are properly set up so that the docs can be updated (I don't have the github permissions to look in settings). Could you confirm that they're set / if they're not set them?

### CODE REVIEW

**Comment by DanielArndt** [comment]
Looks great!

One thing I noticed is that when viewing the documentation, in the left-side menu it appears that "Overview of Sorted Containers" is on the same level as everything below it (ie. "Tokens for Sorted Containers", which is actually a sub-section).

Not sure if this is an issue with the theme, or the way it is contructed.

**Comment by kmsquire** [comment]
@rawls238 I added you as a maintainer on DataStructures.  

@DanielArndt, @StephenVavasis, if you have or create an account on ReadTheDocs, I can add you as well.

**Comment by kmsquire** [comment]
Actually, ignore that last comment: that requires someone who's an owner on JuliaLang, and I'm not, so I don't have access either.

**Comment by kmsquire** [comment]
@StefanKarpinski @ViralBShah can one of you modify the permissions on RTD to allow myself and @rawls238 to maintain DataStructures.jl there?

**Comment by kmsquire** [comment]
Okay, nevermind. I do actually have access.  Sorry for the noise.  ( @rawls238, you should as well.)

**Comment by DanielArndt** [comment]
I created an account and linked it to my github. Is there anything else I need to do?

**Comment by rawls238** [comment]
@danielarndt that's valid. I think that has to do with how I set up the index file, I'll try to change that around before merging this in

**Comment by rawls238** [comment]
@DanielArndt fixed the issue with sorted containers

**Comment by hayd** [comment]
As I commented in the closed #173 this feels like the wrong direction. Nothing in DataStructures has any ? help (which will have to be markdown at some point).

I guess I should **do** rather than complain...

**Comment by DanielArndt** [comment]
@hayd Are you suggesting the best thing to do would be to move all this information to the function definitions, inline as markdown, and wait for the Julia documentation system to be able to generate the documentation?

Sorry if I'm being a little dense, I'm not entirely familiar with the state of the documentation system in the language. I know that base Julia has a lot of documentation in `rst`/sphinx format. Is it moving away from that entirely in favour of documentation generated from inline comments? As far as I remember, I had to change the documentation in order to generate the inline comments in base (which seems backwards).

**Comment by hayd** [comment]
yes, doc generation will be ready soon (next few weeks hopefully). yes, base is moving away from rst entirely. Moving to markdown would make the transition (to inline docstrings and generated online docs) for DataStructures much easier.

**Comment by rawls238** [comment]
sweet, we could try running the doc files through [pandoc](http://pandoc.org/) to convert them to markdown.

**Comment by StefanKarpinski** [comment]
I'm not sure if it's helpful or not, but https://github.com/JuliaLang/julia/tree/sk/markdown implements a Sphinx backend that generates Markdown that's a speculative version of JuliaMarkdown.

**Comment by kmsquire** [comment]
Just pinging @StephenVavasis, who previously explicitly converted the `README` file to *rst* (by hand, I believe), because he was concerned about the expressiveness of markdown.

**Pull request merged**
