### PR TITLE
add Multidict

### PR DESCRIPTION
**Pull request by wildart**
Multi-valued dictionary implementation based on `Dict{K,Vector{V}}`. It behaves as normal dictionary only
* `setindex!` appends new elements to the value vector
* `pop!` removes the last element from the value vector & if the value vector is empty removes key

Some additional functions were added
* `enumerateall` creates enumerator through all (k,v) pairs in the  dictionary
* `count` counts all values in the dictionary ( `length` returns number of keys)
* `size` returns number of keys & values in the dictionary

### CODE REVIEW

**Comment by wildart** [comment]
I wonder maybe `size` would be better way present element count information, so it would return

    (#key, #value) =  size(d)

**Comment by IainNZ** [comment]
It'd be good to somehow knock this and #88 at the same time

**Comment by StephenVavasis** [comment]
@IainNZ, @wildart, @kmsquire 

I can add analogous functions to mimic this functionality to SortedMultiDict, but I have a few concerns:

m[k] = newitem: the proposal here is that this operation acts like a 'push!' instead of an assignment statement, which seems to me inconsistent with the use of assignment elsewhere in Julia.  Perhaps '+=' instead of '='.  What do other readers think?

MultiDict <: Associative: MultiDict does not implement the Associative interface, so I think this subtype declaration should be omitted

**Comment by malmaud** [comment]
Ping @wildart, would be useful to have this. I vote for using `insert!(m, k, newitem)` (as SortedMultiDict does)  instead of `m[k]=newitem` to be more consistent with expectations of assignment.

**Comment by malmaud** [comment]
Superceded by https://github.com/JuliaLang/DataStructures.jl/pull/115

**Pull request closed without merging**
