### PR TITLE
Add sum(::Accumulator)

### PR DESCRIPTION
**Pull request by danielarndt**

### CODE REVIEW

**Comment by kmsquire** [comment]
Hi @danielarndt, not as sure about this one.  Can you give a use case?

**Comment by yuyichao** [comment]
Ref https://github.com/JuliaLang/DataStructures.jl/issues/139

**Comment by kmsquire** [comment]
Thanks, @yuyichao--that explains it.  @danielarndt, can you rebase this?  I assume the export list changed.

(also good to add references in the future... but either way, thanks a lot for submitting the PR)

**Comment by danielarndt** [comment]
Will do @kmsquire -- and thanks for the advice about the refs.

**Comment by danielarndt** [comment]
@kmsquire rebased

**Pull request merged**
