### PR TITLE
sphinx docs

### PR DESCRIPTION
**Pull request by rawls238**
@kmsquire

### CODE REVIEW

**Comment by rawls238** [comment]
sorry this was so delayed - you should be able to just pull this down and run `make html` in the doc folder to auto-generate the documentation

**Comment by DanielArndt** [comment]
This would close #108 -- I'm excited to check this out when I get a minute.

**Comment by rawls238** [comment]
unless anyone has any objections with this, I'm going to try to put this up onto `readthedocs` later today.

**Comment by DanielArndt** [comment]
Finally got around to checking this out. Thanks for doing this. I haven't spent a tonne of time with Sphinx, but are themes added after the build (ie. if you were to upload to readthedocs)? The documentation generated looks very basic, but maybe that's just the state of things currently.

**Comment by rawls238** [comment]
going to try to merge this in and publish this. I'm going to revert the README changes for now and will add them back once the docs are in place.

**Comment by rawls238** [comment]
@DanielArndt it was using the wrong theme, I switched it over to match those of other Julia projects I've seen. Check out the docs here: http://datastructuresjl.readthedocs.org/en/latest/

**Comment by DanielArndt** [comment]
Looks great!

One thing I noticed is that when viewing the documentation, in the left-side menu it appears that "Overview of Sorted Containers" is on the same level as everything below it (ie. "Tokens for Sorted Containers", which is actually a sub-section).

Not sure if this is an issue with the theme, or the way it is contructed.

**Comment by kmsquire** [comment]
Looks good--thanks Guy!

**Pull request merged**
