### PR TITLE
0.4 bindings deprecation

### PR DESCRIPTION
**Pull request by yuyichao**

### CODE REVIEW

**Comment by StephenVavasis** [comment]
Yichao,

I tried to change Nothing to Void myself when I was preparing the latest update but discovered that Void is undefined in Julia 0.3.  Let us see if this branch passes the Travis testing..  Maybe there is 
```
@compat Void
```
?
-- Steve

**Comment by yuyichao** [comment]
Hmm seems that this is missing from Compat.

**Comment by yuyichao** [comment]
May require https://github.com/JuliaLang/Compat.jl/pull/139 on 0.3 .

**Comment by yuyichao** [comment]
CI restarted. Should still wait for a new tag in Compat.

**Comment by yuyichao** [comment]
Bump Compat requirement to 0.7.1

**Pull request merged**
