### PR TITLE
Add warning on unordered to ordered conversion. Fixes #216

### LINKED ISSUE #216: Should there be conversion from Dict to OrderedDict?
Since `convert(Vector{Int}, Set([1,2,3]))` is not defined, shouldn't `convert(OrderedDict{Int, Int}, Dict(1=>2, 3=>4))` also be undefined? `OrderedDict` cares about the ordering, but the conversion gives it a random one, which isn't meaningful.

### PR DESCRIPTION
**Pull request by cstjean**
I tried to match the tone from Base, but please let me know if anything sounds off.

### CODE REVIEW

**Comment by kmsquire** [comment]
@cstjean, sorry for the delay on this, but would you be able to add some tests?

**Comment by kmsquire** [comment]
(Also, there is a minor conflict.)

**Comment by cstjean** [comment]
Can I test the warnings? Or do you mean to make sure that `is_ordered(Dict)==true`?

**Comment by kmsquire** [comment]
Just testing `is_ordered` (for all of the dictionaries for which it is defined) would be fine.  Base runs julia with `--depwarn=error`, which could be caught, but I don't think packages are tested that way by default.

**Comment by cstjean** [comment]
Tested and rebased.

**Comment by kmsquire** [comment]
Thanks!

**Comment by kmsquire** [comment]
For testing the deprecation see https://github.com/JuliaLang/julia/issues/20348.

**Pull request merged**
