### PR TITLE
implement values(::Accumulator)

### PR DESCRIPTION
**Pull request by yuyichao**
Ref #139

### CODE REVIEW

**Comment by yuyichao** [comment]
Does anyone have any issue with this?

**Comment by yuyichao** [comment]
Will merge tomorrow if no one objects.

**Comment by danielarndt** [comment]
@yuyichao Seems to be pretty dead here. Do you know if this is still actively maintained?

**Comment by yuyichao** [comment]
I don't think this has a maintainer (i.e. no one is specifically in charge of it) but it's certainly not dead.

Feel free to ping people on your PR (either just `ping` or use `git blame` to find the people that might be most qualified for reviewing).

**Pull request merged**
