### PR TITLE
More deque tests

### PR DESCRIPTION
**Pull request by kshyatt**
Testing the IO methods and `empty!`.

### CODE REVIEW

**Comment by StephenVavasis** [comment]
Just wondering about checking IO methods with this kind of code:

```julia
@test sprint(dump,q) == "Deque (length = 0, nblocks = 1)\nblock 1 [1:0] ==> \n"
```
It seems like this would be quite brittle since details of how ``show`` works for built-in types could change from one Julia build to the next.  On the other hand, I don't have a proposal for a better way to test a ``show`` method.

**Comment by kshyatt** [comment]
I agree that it's brittle, and I also don't have any better suggestions. Does this (now that I've updated it to not fail!) look ok to you?

**Comment by StephenVavasis** [comment]
Maybe just ``@test length(sprint(show,a)) > 0``?  At least this runs the code and confirms that it returns something?

**Comment by kshyatt** [comment]
@StephenVavasis I've updated the PR per your comments. Is this ok?

**Comment by StephenVavasis** [comment]
OK with me.  Thanks for taking care of this.

**Pull request merged**
